sudo: false
language: python
notifications:
  email:
    recipients:
      - chenjiandongx@qq.com
    on_success: always # default: change
    on_failure: always # default: always
python:
  - 3.7
  - 3.6
  - 3.5
before_install:
  - pip install -r test/requirements.txt
script:
  - python setup.py install
  - cd test
  - nosetests --with-coverage --cover-package test
after_success:
  - cd test
  - codecov
